 version: '3.1'

 services:
   clearingcost:
    container_name: clearingcost
    build: clearingcost
    ports:
      - 9080:9080
   iincache:
    container_name: iincache
    build: iincache
    ports:
      - 9082:9082
   summer:
    container_name: summer
    build: summer
    ports:
      - 9081:9081
    environment:
      iincache.ip: iincache
      iincache.http.port: 9082
      clearingcost.ip: clearingcost
      clearingcost.http.port: 9080
    depends_on:
      - clearingcost
      - iincache
