 version: '3.1'

 services:
   clearingcost:
    container_name: clearingcost
    build: clearingcost
    ports:
      - 9080:9080
   summer:
    container_name: summer
    build: summer
    ports:
      - 9081:9081
    